### ISSUE TITLE
assigned routes need to send an email out to the assignee

### ISSUE THREAD

**Issue by skeltont** [protoscend/protoscend#166] opened 2016-11-21 05:12 UTC
title

**Comment by jonahgeorge** [comment] 2016-11-21 16:47
Email content?
If the route is re-assigned (if we can do that), should an email be sent to the new owner?
This is mainly a notification for the owner of route, correct? Since an admin will be assigning users

**Comment by jonahgeorge** [comment] 2016-11-21 16:48
Dupe of #156

**Closed as completed** 2016-11-21 17:22 UTC
Labels: pri: important, type: feature
